version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - backend  
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    volumes:
      - ./backend:/app  # Map backend folder to the container
    stdin_open: true
    tty: true
